---
id: Kolab_Cli
name: Kolab_Cli
full: Kolab storage command line interface library
description: >
  A set of utilities to deal with the various aspects of a Kolab server as
  backend. The primary focus is dealing with the data stored in IMAP.
list: dev
